# Generated by Django 4.2.29 on 2026-03-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-certificate', help_text='Font Awesome icon class', max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': '✅ About Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='ABOUT US', max_length=100)),
                ('title_line1', models.CharField(default='Engineering', max_length=200)),
                ('title_line2', models.CharField(default='Excellence', help_text='Sehemu yenye gradient color', max_length=200)),
                ('paragraph1', models.TextField(default='Founded in 2022, M2N Engineering has rapidly established itself as a premier electrical contractor in Tanzania. Based in Kilombero, Morogoro, we combine local expertise with global standards to deliver exceptional electrical solutions. Beyond electrical work, we have expanded our capabilities to include civil construction and plumbing works, providing integrated infrastructure solutions for residential, commercial, and industrial clients across the country.')),
                ('paragraph2', models.TextField(default="Our team of certified engineers and technicians brings decades of combined experience across residential, commercial, and industrial projects. We don't just complete projects – we create lasting partnerships built on trust, quality, and innovation.")),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': '🏢 About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='GET IN TOUCH', max_length=100)),
                ('title_line1', models.CharField(default='Contact', max_length=200)),
                ('title_line2', models.CharField(default='Us', help_text='Sehemu yenye gradient color', max_length=200)),
                ('info_card_title', models.CharField(default='Contact Information', max_length=100)),
                ('form_card_title', models.CharField(default='Send Inquiry', max_length=100)),
                ('whatsapp_message_header', models.CharField(default='*NEW PROJECT INQUIRY - M2N ENGINEERING*', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': '📞 Contact Section',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-certificate', help_text='Font Awesome icon class', max_length=50)),
                ('title', models.CharField(help_text='Mfano: High Voltage, Experience, Team, Coverage', max_length=100)),
                ('value', models.CharField(help_text='Mfano: 33kV Certified, 4+ Years Excellence', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': '🏆 Credentials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='fas fa-bolt', help_text='Font Awesome icon class ya badge (mfano: fas fa-bolt)', max_length=50)),
                ('badge_text', models.CharField(default='CRB CLASS V · BRELA INCORPORATED', max_length=200)),
                ('title_line1', models.CharField(default='Powering', help_text='Sehemu ya kwanza ya kichwa (rangi nyeupe)', max_length=200)),
                ('title_line2', models.CharField(default="Tanzania's Future", help_text='Sehemu ya pili ya kichwa (gradient color)', max_length=200)),
                ('description', models.TextField(default='M2N Engineering is a premier electrical contracting company based in Kilombero, Morogoro. We deliver world-class electrical solutions across Tanzania with uncompromising quality, safety, and professionalism. In addition to our comprehensive electrical services, we also specialize in civil construction and plumbing works, offering integrated solutions for all your construction and infrastructure needs. From foundation to finish, our team of certified experts delivers excellence in every project.')),
                ('btn_primary_text', models.CharField(default='Start Project', max_length=100)),
                ('btn_primary_icon', models.CharField(default='fas fa-rocket', max_length=50)),
                ('btn_primary_url', models.CharField(default='#contact', max_length=100)),
                ('btn_secondary_text', models.CharField(default='Explore Services', max_length=100)),
                ('btn_secondary_icon', models.CharField(default='fas fa-eye', max_length=50)),
                ('btn_secondary_url', models.CharField(default='#services', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': '🏠 Hero Section (Home)',
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Mfano: 33kV, 50+, CRB V', max_length=50)),
                ('label', models.CharField(help_text='Mfano: High Voltage, Projects, Class Five', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': '📊 Hero Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL ya picha ya mradi')),
                ('category', models.CharField(help_text='Mfano: High Voltage, Power Distribution', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='Mfano: Kilombero, Morogoro', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Mradi mkubwa unaochukua nafasi mbili (featured card)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': '📁 Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='PORTFOLIO', max_length=100)),
                ('title_line1', models.CharField(default='Featured', max_length=200)),
                ('title_line2', models.CharField(default='Projects', help_text='Sehemu yenye gradient color', max_length=200)),
            ],
            options={
                'verbose_name': 'Projects Section',
                'verbose_name_plural': '🏗️ Projects Section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='URL ya picha ya huduma')),
                ('icon', models.CharField(default='fas fa-bolt', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('in_contact_form', models.BooleanField(default=True, help_text='Ionyeshwe kwenye dropdown ya contact form?')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': '🔧 Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='WHAT WE DO', max_length=100)),
                ('title_line1', models.CharField(default='Our', max_length=200)),
                ('title_line2', models.CharField(default='Services', help_text='Sehemu yenye gradient color', max_length=200)),
                ('intro_paragraph', models.TextField(default='M2N Engineering provides comprehensive electrical solutions tailored to meet the diverse needs of our clients across Tanzania. From residential wiring to high-voltage industrial installations, our team of certified experts delivers excellence in every project. Each service is backed by our commitment to quality, safety, and customer satisfaction.')),
                ('intro_highlight', models.CharField(default='We offer 21 specialized electrical services', max_length=200)),
                ('intro_icon', models.CharField(default='fas fa-bolt', max_length=50)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': '⚡ Services Section',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='M2N ENGINEERING', max_length=200)),
                ('company_tagline', models.CharField(default='ELECTRICAL CONTRACTORS · TANZANIA', max_length=200)),
                ('logo_url', models.URLField(blank=True, default='image/logo.png', help_text="URL ya picha ya logo (inaweza kuwa relative kama 'image/logo.png' au URL kamili)")),
                ('phone1', models.CharField(default='+255 629 625 288', max_length=30)),
                ('phone2', models.CharField(default='+255 695 550 288', max_length=30)),
                ('whatsapp_number', models.CharField(default='255629625288', help_text='Nambari ya WhatsApp bila + (mfano: 255629625288)', max_length=30)),
                ('email', models.EmailField(default='info@m2nengineering.co.tz', max_length=254)),
                ('address', models.CharField(default='Mkamba Street, Kidatu Ward, Kilombero, Morogoro, Tanzania', max_length=300)),
                ('working_hours', models.CharField(default='Mon-Fri: 8:00 - 17:00 | Sat: 8:00 - 13:00', max_length=200)),
                ('crb_number', models.CharField(default='CRB Class V', max_length=100)),
                ('brela_number', models.CharField(default='BRELA #192412951', max_length=100)),
                ('tin_number', models.CharField(default='TIN: 192-412-951', max_length=100)),
                ('license_year', models.CharField(default='2027', max_length=20)),
                ('meta_description', models.TextField(blank=True, default='M2N Engineering is a premier electrical contracting company based in Kilombero, Morogoro. We deliver world-class electrical solutions, civil construction, and plumbing works across Tanzania.')),
                ('meta_keywords', models.TextField(blank=True, default='electrical contractors Tanzania, civil construction, plumbing works, Kilombero, Morogoro, M2N Engineering')),
                ('og_image_url', models.URLField(blank=True, default='https://m2nengineeringcoltd.onrender.com/image/logo.png', help_text='Open Graph image URL kwa social media previews')),
                ('site_url', models.URLField(blank=True, default='https://m2nengineeringcoltd.onrender.com', help_text='URL kamili ya website')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': '⚙️ Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField(help_text='URL kamili ya ukurasa wako wa social media')),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-instagram', 'Instagram'), ('fab fa-twitter', 'Twitter/X'), ('fab fa-x-twitter', 'X (Twitter New)'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-youtube', 'YouTube'), ('fab fa-tiktok', 'TikTok'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-telegram', 'Telegram'), ('fas fa-globe', 'Other')], default='fab fa-facebook-f', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': '🌐 Social Media Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='website.service')),
            ],
            options={
                'verbose_name': 'Service Tag',
                'verbose_name_plural': 'Service Tags',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
    ]
